// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dplock

import (
	"context"
	"sync"

	"github.com/ONSdigital/dp-mongodb/v3/dplock"
	lock "github.com/square/mongo-lock"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ dplock.Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			UnlockFunc: func(ctx context.Context, lockID string) ([]lock.LockStatus, error) {
//				panic("mock out the Unlock method")
//			},
//			XLockFunc: func(ctx context.Context, resourceName string, lockID string, ld lock.LockDetails) error {
//				panic("mock out the XLock method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// UnlockFunc mocks the Unlock method.
	UnlockFunc func(ctx context.Context, lockID string) ([]lock.LockStatus, error)

	// XLockFunc mocks the XLock method.
	XLockFunc func(ctx context.Context, resourceName string, lockID string, ld lock.LockDetails) error

	// calls tracks calls to the methods.
	calls struct {
		// Unlock holds details about calls to the Unlock method.
		Unlock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LockID is the lockID argument value.
			LockID string
		}
		// XLock holds details about calls to the XLock method.
		XLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ResourceName is the resourceName argument value.
			ResourceName string
			// LockID is the lockID argument value.
			LockID string
			// Ld is the ld argument value.
			Ld lock.LockDetails
		}
	}
	lockUnlock sync.RWMutex
	lockXLock  sync.RWMutex
}

// Unlock calls UnlockFunc.
func (mock *ClientMock) Unlock(ctx context.Context, lockID string) ([]lock.LockStatus, error) {
	if mock.UnlockFunc == nil {
		panic("ClientMock.UnlockFunc: method is nil but Client.Unlock was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		LockID string
	}{
		Ctx:    ctx,
		LockID: lockID,
	}
	mock.lockUnlock.Lock()
	mock.calls.Unlock = append(mock.calls.Unlock, callInfo)
	mock.lockUnlock.Unlock()
	return mock.UnlockFunc(ctx, lockID)
}

// UnlockCalls gets all the calls that were made to Unlock.
// Check the length with:
//
//	len(mockedClient.UnlockCalls())
func (mock *ClientMock) UnlockCalls() []struct {
	Ctx    context.Context
	LockID string
} {
	var calls []struct {
		Ctx    context.Context
		LockID string
	}
	mock.lockUnlock.RLock()
	calls = mock.calls.Unlock
	mock.lockUnlock.RUnlock()
	return calls
}

// XLock calls XLockFunc.
func (mock *ClientMock) XLock(ctx context.Context, resourceName string, lockID string, ld lock.LockDetails) error {
	if mock.XLockFunc == nil {
		panic("ClientMock.XLockFunc: method is nil but Client.XLock was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ResourceName string
		LockID       string
		Ld           lock.LockDetails
	}{
		Ctx:          ctx,
		ResourceName: resourceName,
		LockID:       lockID,
		Ld:           ld,
	}
	mock.lockXLock.Lock()
	mock.calls.XLock = append(mock.calls.XLock, callInfo)
	mock.lockXLock.Unlock()
	return mock.XLockFunc(ctx, resourceName, lockID, ld)
}

// XLockCalls gets all the calls that were made to XLock.
// Check the length with:
//
//	len(mockedClient.XLockCalls())
func (mock *ClientMock) XLockCalls() []struct {
	Ctx          context.Context
	ResourceName string
	LockID       string
	Ld           lock.LockDetails
} {
	var calls []struct {
		Ctx          context.Context
		ResourceName string
		LockID       string
		Ld           lock.LockDetails
	}
	mock.lockXLock.RLock()
	calls = mock.calls.XLock
	mock.lockXLock.RUnlock()
	return calls
}
