// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-mongodb/dplock"
	"github.com/square/mongo-lock"
	"sync"
)

var (
	lockPurgerMockPurge sync.RWMutex
)

// Ensure, that PurgerMock does implement dplock.Purger.
// If this is not the case, regenerate this file with moq.
var _ dplock.Purger = &PurgerMock{}

// PurgerMock is a mock implementation of dplock.Purger.
//
//     func TestSomethingThatUsesPurger(t *testing.T) {
//
//         // make and configure a mocked dplock.Purger
//         mockedPurger := &PurgerMock{
//             PurgeFunc: func() ([]lock.LockStatus, error) {
// 	               panic("mock out the Purge method")
//             },
//         }
//
//         // use mockedPurger in code that requires dplock.Purger
//         // and then make assertions.
//
//     }
type PurgerMock struct {
	// PurgeFunc mocks the Purge method.
	PurgeFunc func() ([]lock.LockStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// Purge holds details about calls to the Purge method.
		Purge []struct {
		}
	}
}

// Purge calls PurgeFunc.
func (mock *PurgerMock) Purge() ([]lock.LockStatus, error) {
	if mock.PurgeFunc == nil {
		panic("PurgerMock.PurgeFunc: method is nil but Purger.Purge was just called")
	}
	callInfo := struct {
	}{}
	lockPurgerMockPurge.Lock()
	mock.calls.Purge = append(mock.calls.Purge, callInfo)
	lockPurgerMockPurge.Unlock()
	return mock.PurgeFunc()
}

// PurgeCalls gets all the calls that were made to Purge.
// Check the length with:
//     len(mockedPurger.PurgeCalls())
func (mock *PurgerMock) PurgeCalls() []struct {
} {
	var calls []struct {
	}
	lockPurgerMockPurge.RLock()
	calls = mock.calls.Purge
	lockPurgerMockPurge.RUnlock()
	return calls
}
