---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.11-bookworm

inputs:
  - name: dp-mongodb
    path: dp-mongodb

run:
  path: dp-mongodb/ci/scripts/build.sh
